spring.application.name=serverstatus
spring.datasource.url=jdbc:postgresql://localhost:5432/serverstatus
spring.datasource.username=postgres
spring.datasource.password=4444
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
